version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-fast
    environment:
      POSTGRES_DB: result
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_fast_api
    hostname: rabbitmq_fast_api
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 30s
      retries: 10

  fast_api_services:
    build:
      dockerfile: Dockerfile
      context: .
    image: fast_api_app
    container_name: fast_api
    hostname: fast_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      bash -c  "chmod +x run.sh && ./run.sh"


