version: "3.9"

services:
  db_fast_api:
    hostname: postgres_fast_api
    image: postgres:latest
    container_name: postgres_fast_api
    ports:
      - '5432:5432'
    volumes:
      - ~/.pg/pg_data/user:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq_fast_api
    hostname: rabbitmq_fast_api
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 30s
      retries: 10
    restart: always


  fast_api_services:
    build:
      dockerfile: Dockerfile
      context: .
    image: fast_api_app
    container_name: fast_api
    hostname: fast_api
    depends_on:
      - db_fast_api
      - rabbitmq
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      bash -c  "chmod +x run.sh && ./run.sh"



